### ISSUE TITLE
Data Change

### ISSUE THREAD

**Issue by swiftan** [Hipo/university-domains-list#111]
Hi Yiğit,
Current Hacettepe University (hun.edu.tr) domain is old one. Currently, Hacettepe University using "hacettepe.edu.tr". Can you please add/fix it ?

**Comment by Seanland** [comment]
Hi @swiftan , even though the domain is "old" it appears to be active.  I am not sure if you know or not?  I guess both should remain active?

**Comment by Seanland** [comment]
@swiftan I added both - if the old one goes down we can always remove it later :)

**Comment by swiftan** [comment]
Both are them active.

2018-01-20 8:32 GMT-08:00 Sean Clarke <notifications@github.com>:
