### ISSUE TITLE
Adding university

### ISSUE THREAD

**Issue by Tokyx** [Hipo/university-domains-list#154]
Can you add this please ? Thank you.

{
    "web_pages": [
        "https://www.mmibordeaux.com/"
    ],
    "alpha_two_code":  null,
    "state-province": null,
    "country": "France",
    "domains": [
        "mmibordeaux.com"
    ],
    "name": "DUT MMI - Université Bordeaux Montaigne"
}

**Comment by yigitguler** [comment]
@Tokyx can you please open a PR? Also alpha_two_code should be fr.

**Comment by LachlanMarnham** [comment]
Shall I open a PR? I'll check the details first.
