### ISSUE TITLE
adding university

### ISSUE THREAD

**Issue by motconvoi** [Hipo/university-domains-list#158]
Please add domain for Duy Tan University from Viet Nam, thanks for help
 {
    "web_pages": [
      "http://www.dtu.edu.vn/"
    ],
    "name": "Duy Tan University",
    "alpha_two_code": "VN",
    "state-province": null,
    "domains": [
      "dtu.edu.vn"
    ],
    "country": "Viet Nam"
  },

**Comment by yigitguler** [comment]
Please open a PR. Thank you.
