### ISSUE TITLE
Duplicate Names with Same Domains & Web pages

### ISSUE THREAD

**Issue by samapriya** [Hipo/university-domains-list#185]
Hi there,
I see that there are issues with same website and domain is associated with multiple entries such as the following is this expected behaviour? there are more than one of such occurances

```
{
"web_pages": [
"http://www.sjsu.edu/"
],
"name": "California State University, San Jose",
"alpha_two_code": "US",
"state-province": null,
"domains": [
"sjsu.edu"
],
"country": "United States"
},
```
and
```
{
"web_pages": [
"http://www.sjsu.edu/"
],
"name": "San Jose State University",
"alpha_two_code": "US",
"state-province": null,
"domains": [
"sjsu.edu"
],
"country": "United States"
},
```

**Comment by yigitguler** [comment]
This is a mistake.  We should write a test that checks that domain names and web_pages are unique.

**Comment by zsubzwary** [comment]
This particular entry has been fixed ....

@yigitguler Why don’t you add a simple JSON testing check with TRAVIS so that the JSON files could be checked for Syntax error in all the PR ??

**Comment by yigitguler** [comment]
@zsubzwary this already exists here: https://github.com/Hipo/university-domains-list/blob/7265f807f1d71c502e4e06916d85ff0a53d87d32/tests/main.py#L6

**Comment by zsubzwary** [comment]
then why didn't those tests run during a PR ???

**Comment by yigitguler** [comment]
They ran. But this is not a syntax error.

**Comment by zsubzwary** [comment]
if you [see here in this pr](https://github.com/Hipo/university-domains-list/pull/186/checks) there haven been any checks !!

**Comment by yigitguler** [comment]
https://travis-ci.org/Hipo/university-domains-list/pull_requests

**Comment by zsubzwary** [comment]
Okay it did occurred, but why ain't they showing up in the **CHECKS** section of a PR ??
