### ISSUE TITLE
Add countryCode : ISO3166-1-Alpha-2 field

### ISSUE THREAD

**Issue by dolftax** [Hipo/university-domains-list#19]
When mapping this JSON across various other data sets, it is harder to search because of the mismatch of names. For example, the universal name of Russia is 'Russian Federation' but here it is referred to as 'Russia.'

It would be better to add another field `countryCode` which says the universal alpha2 country code of the specific country.

**Comment by dolftax** [comment]
If you guys have some spare time to contribute, then go ahead with it. Else, assign it to me. I will do it over the weekend :blush:

**Comment by yigitguler** [comment]
You're absolutely right. It would be great if you could parse this data and add a country code field
