### ISSUE TITLE
invalid json

### ISSUE THREAD

**Issue by nosilver4u** [Hipo/university-domains-list#193]
When attempting to update my local list this morning, it seemed that my PHP script was failing to grok the JSON file at https://github.com/Hipo/university-domains-list/blob/master/world_universities_and_domains.json

I copied the contents to JSONlint.com, and it gives this:
```
Error: Parse error on line 37474:
...fi/"		],		"name": Laurea University of
---------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```
Manual inspection of the file shows that Laurea University of Applied Sciences was missing a preceding quote. After adding the quote, my local script worked just fine, and JSONlint.com verifies the file as valid JSON.

**Comment by zsubzwary** [comment]
@yigitguler didn't you checked the tests before merging ?
[Test Failed](https://travis-ci.org/Hipo/university-domains-list/builds/529655870)

**Comment by yigitguler** [comment]
Thanks @nosilver4u, it is fixed now.

**Comment by nosilver4u** [comment]
Thanks for all your hard work @yigitguler 
This project is an amazing resource, and immensely helpful.
