### ISSUE TITLE
Universidad Loyola Andalucía

### ISSUE THREAD

**Issue by eldiegos** [Hipo/university-domains-list#196]
Please add this University created in 2011 in Spain.
Thank you very much.

{
    "web_pages": [
      "https://www.uloyola.es/"
    ],
    "name": "Universidad Loyola Andalucía",
    "alpha_two_code": "ES",
    "state-province": Andalusia,
    "domains": [
      "uloyola.es"
    ],
    "country": "Spain"
  }

**Comment by yigitguler** [comment]
Fixed.
