### ISSUE TITLE
Renaming of Fachhochschule Ingolstadt to Technische Hochschule Ingolstadt

### ISSUE THREAD

**Issue by inloox-dev** [Hipo/university-domains-list#208]
Old entry:

   "web_pages": [
      "http://www.fh-ingolstadt.de/"
    ],
    "name": "Fachhochschule Ingolstadt",
    "alpha_two_code": "DE",
    "state-province": null,
    "domains": [
      "fh-ingolstadt.de"
    ],

New entry:

   "web_pages": [
      "https://www.thi.de/"
    ],
    "name": "Technische Hochschule Ingolstadt",
    "alpha_two_code": "DE",
    "state-province": null,
    "domains": [
      "thi.de"
    ],

**Comment by onlined** [comment]
You should open a PR for changing the JSON file.

**Comment by yigitguler** [comment]
@Hskl14 solved this issue.
