### ISSUE TITLE
Correct an university name

### ISSUE THREAD

**Issue by nuhkoca** [Hipo/university-domains-list#35]
hi, when I was having a look at your API, I encountered a typo. Could you please correct the name for that university is given below. Thanks for the API.

web_page: "http://www.mehmetakif.edu.tr/",
country: "Turkey",
domain: "mehmetakif.edu.tr",
name: "Mehemet Akif Ersoy University", --> this one.
alpha_two_code: "TR"

**Comment by yigitguler** [comment]
Hi @nuhkoca,

Thanks for reporting. We will appreciate if you could open a PR.

Best

**Comment by yigitguler** [comment]
@hamedty resolved this issue.
