### ISSUE TITLE
Schools with Multiple Domains

### ISSUE THREAD

**Issue by hamedty** [Hipo/university-domains-list#39]
There are some schools with multiple domains. e.g.:

University of Illinois Urbana-Champaign
- illinois.edu
- uiuc.edu

Although the last one will be redirected to the the first one, but for sake of email verification you might need both in the DB. Their faculties have emails from both domains.

My suggestion is to convert "domain" field from a string to list of strings and for cases like this we can add multiple entries.

If everyone are OK with this scheme I can create a PR.

**Comment by yigitguler** [comment]
Hi,

That makes sense, we received many PRs for change of domains for the same university. Apparently, many universities have different domains. While first making this list, I wasn't aware of this situation.

We might do this change, however, we should avoid creating problems for existing users (at least for a month or two)

Right now we have a key named `domain ` in the json response. We can add a new field called `domains` and provide a list containing domains there. 

Or we can remove `domain` field immediately.

**Comment by hamedty** [comment]
That sounds good. I will create a PR once I get a chance.

**Comment by yigitguler** [comment]
Thank you.

**Comment by jpuck** [comment]
uark.edu will be rebranding sometime in the near future to arkansas.edu, but they will retain use of uark.edu.

I would suggest adding an optional `domains` field as an *array* of strings for easier processing. Keep `domain` for backwards compatibility and include the primary domain there.

**Comment by konstardiy** [comment]
I think that "domain" field can be kept as strategy of transition, and return a space-separated list for multiple domains. Like "illinois.edu uuic.edu"...
Of course this can create problems so better to provide some versioning to api and list format, and use "domains" for data of v2 version, with array of strings for domains property, and keep v1 data with single-domain data... With a plan to deprecate v1 format few months later.

**Comment by yigitguler** [comment]
We will separate source files and outputs. The source file will contain a list of domains. And we will have 2 outputs. One for the old implementation, one for the new one.

**Comment by yigitguler** [comment]
After some discussion, we decided to follow a simpler approach. We changed the data format :/ Now we have "domains" array and "web_pages" array. I think this data structure is much more closer to the real world.
