### ISSUE TITLE
Can filter by domain?

### ISSUE THREAD

**Issue by blockchainGuru1018** [Hipo/university-domains-list#400]
in my case, the input data is a student's email address.
and I need to check the student email is in the JSON file.
so actually I need to know the user email's domain part is in the JSON file.

It looks like doesn't support this feature.

**Comment by yigitguler** [comment]
The list contains the domain information, so you can actually filter by the domain name of the email you have.

**Comment by blockchainGuru1018** [comment]
> The list contains the domain information, so you can actually filter by the domain name of the email you have.

I need to filter the domain by my php server.
could you let me know the query and endpoints, so I hope you provide me full endpoint url of it.
Thanks

**Comment by yigitguler** [comment]
You can import the list to your PHP code.  This is the repository of the university domains. There is another repo for the tiny webserver, you can also open a PR for a new type of query.
