### ISSUE TITLE
Update Indonesian university

### ISSUE THREAD

**Issue by mamat-rahmat** [Hipo/university-domains-list#42]
Hi,
I want to update Indonesian university data to the current state. There is only some popular university listed here and my quick scan saw that some university have changed their website/domain. Based on our [Ministry of Higher Education statistics](http://forlap.ristekdikti.go.id/perguruantinggi/homegraphpt), currently we have (about) 4507 university listed.
I am planning to create a script to scrap these data and add that to here. What do you think?
However in our beloved developed country, some university haven't use .ac.id/.edu domain for their website yet and use gmail even for their official email. Is it counted as passing criteria here?

**Comment by yigitguler** [comment]
Hi Mamat,

I think it will be great to include unlisted ones as well. According to the website that you sent, more than half of those instutions are listed as "High Schools" (Sekolah Tinggi) We should avoid high schools being listed.

We dont need their email addresses, but if they provide an email service for their students, we should add that domain as well. (Not Gmail for sure)

Most of the people using this links aims to detect if an email address belongs to an university student / academician. So we should act accordingly.

**Comment by mamat-rahmat** [comment]
@yigitguler No, Sekolah Tinggi does not directly translated into High School. Sekolah tinggi is another type of Higher Education that offer focused (one cluster of science) education while in Indonesia "High School" named "Sekolah Menengah Atas"

About email, sorry for my unclear question. I mean, even their official contact email are using gmail, so big chance that their student/academician also does not have email that use university domain. Okay, i will filter this according to the mission (student/academician detection).

I am working on it and will ask you if i have any question. Thanks.

**Comment by yigitguler** [comment]
Thank you and good luck!
