### ISSUE TITLE
Add Miami Dade College

### ISSUE THREAD

**Issue by bianca-codaio** [Hipo/university-domains-list#431]
{
    "web_pages": [
      "http://www.mdc.edu"
    ],
    "name": "Miami Dade College”,
    "alpha_two_code": "US",
    "state-province": null,
    "domains": [
      “mdc.edu”
    ],
    "country": "United States"
  },

**Comment by co-bby** [comment]
Already added

**Comment by yigitguler** [comment]
Thanks @co-bby
