### ISSUE TITLE
Duplicate universities

### ISSUE THREAD

**Issue by DanVi007** [Hipo/university-domains-list#460]
Hi, why do I get duplicate universities?
![image](https://user-images.githubusercontent.com/80539964/218332528-c07a61fc-5167-4ebb-8237-1018f4e88da1.png)
![image](https://user-images.githubusercontent.com/80539964/218332647-cdbd9c8a-e5e6-4b60-a923-00d4f8290cf6.png)

**Comment by yigitguler** [comment]
Please open this ticket to https://github.com/Hipo/university-domains-list-api/
