### ISSUE TITLE
Wrong character in name and country

### ISSUE THREAD

**Issue by zain756** [Hipo/university-domains-list#47]
Please update country and name for following:

  {
      "alpha_two_code": "CI",
      "country": "C\u00f4te d'Ivoire",
      "domain": "uabobo.ci",
      "name": "Universit\u00e9 d'Abobo-Adjam\u00e9",
      "web_page": "http://www.uabobo.ci/"
  },
  {
      "alpha_two_code": "CI",
      "country": "C\u00f4te d'Ivoire",
      "domain": "ubouake.ci",
      "name": "Universit\u00e9 de Bouak\u00e9",
      "web_page": "http://www.ubouake.ci/"
  },
  {
      "alpha_two_code": "CI",
      "country": "C\u00f4te d'Ivoire",
      "domain": "univ-cocody.ci",
      "name": "Universit\u00e9 de Cocody",
      "web_page": "http://www.univ-cocody.ci/"
  },

**Comment by yigitguler** [comment]
Hi Zain,

Please open a PR.
