### ISSUE TITLE
Wrong university information

### ISSUE THREAD

**Issue by Quack-29** [Hipo/university-domains-list#656]
{
    "web_pages": ["http://www.hcmuns.edu.vn/"], => **This should be** "https://hcmus.edu.vn"
    "name": "Ho Chi Minh City University of Natural Sciences", **This should be** "Ho Chi Minh City University of Science"
    "alpha_two_code": "VN",
    "state-province": null,
    "domains": ["hcmuns.edu.vn"], **This should be** "hcmus.edu.vn"
    "country": "Viet Nam"
  }

**Comment by SharvariTatachar** [comment]
i can look at this
