### ISSUE TITLE
University Logos

### ISSUE THREAD

**Issue by extwiii** [Hipo/university-domains-list#79]
Hi Guys,

You have done a great job! Well done, really useful source to be honest.

I just want to ask that is there any way to get universities logos'?

That would be more useful if it can be implemented.

Let me know if you are planning something like that I would love to help.

Thanks

**Comment by yigitguler** [comment]
Hi,

Thank you! As far as I know, there isn't such a database. I don't know your usecase but if a very small icon will be enough, you can use /favicon.ico :)

Best

**Comment by yigitguler** [comment]
Also, we will be changing the data structure soon. Because we learned that many universities has multiple domains. However I cannot imagine any feasible way to get the logos of the universities programmatically.

**Comment by extwiii** [comment]
I am trying to show users university logos with their names to pick them.
I try to add a new field to your JSON and I will call it img.
If I succeed new JSON will be like this;
{
        "alpha_two_code": "US",
        "country": "United States",
        "domain": "mbl.edu",
        "name": "Marine Biological Laboratory",
        "web_page": "http://www.mbl.edu/",
        "img": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQjSfquVqz6BEPrmiW3ZpD01ipkvyg0xwJ7sIeoAk4orNpCtpE23MFGS8"
    }

**Comment by yigitguler** [comment]
Sounds great!
Could you please use "logo" instead of "img"? I believe that it will be more easy to understand that way.

Regards

**Comment by extwiii** [comment]
Hi Yigit,

I know it has been a long time to get back to you but it was really hard to collect data from Google especially when you are getting so many 503 errors.

I have managed to collect some valuable image link for your JSON data and I thought that you might be interested in.

Oops, I just realise that your advice to use logo instead of img, I believe you can overwrite easily with one for loop if you want.

Some of the links are irrelevant due to Google put them first place when you search the same term of mine.

You can check from below repo to see how is new json data looks like. Please find sorted.json file under data folder.

https://github.com/extwiii/React-Node-Google-Search

If you like data please let me know I can fork your repo and send PR to merge it.

Thanks

**Comment by yigitguler** [comment]
Hi,

I checked some of them and they look neat. Thank you.

 - Did you curate the images and eliminate the ones that are not logos?
 - Are the dimensions of the images same?

**Comment by yigitguler** [comment]
Also It would be great if you could change the name of the field as well.  :)

**Comment by extwiii** [comment]
Hi,

I try to get 300x300 picture but need to test it first.

Every university has a logo but some of them are irrelevant due to Google Search engine that renders the wrong image its first result. 

Thanks

**Comment by alanhamlett** [comment]
This library shouldn't include logos since anyone can easily automate getting a University logo:

* fetch the website and look for favicon meta tags
* look for `favicon.ico` at website root url
* use free logo apis, for ex: https://clearbit.com/docs?shell#logo-api

**Comment by Shubham121s** [comment]
> Hi Guys,
> 
> You have done a great job! Well done, really useful source to be honest.
> 
> I just want to ask that is there any way to get universities logos'?
> 
> That would be more useful if it can be implemented.
> 
> Let me know if you are planning something like that I would love to help.
> 
> Thanks

yes i wanted university logo
