### ISSUE TITLE
Please add Georgian Free University

### ISSUE THREAD

**Issue by konstardiy** [Hipo/university-domains-list#91]
As I see, the record for this university should be like this:
`{
   "alpha_two_code": "GE",
   "country": "Georgia",
   "domain": "freeuni.edu.ge",
   "name": "Free University of Tbilisi",
   "web_page": "http://freeuni.edu.ge/"
}`

Thanks for your effort to keep this list fresh and actual!

**Comment by yigitguler** [comment]
Thank you. Could you please open a PR?

Thanks.
